### ISSUE TITLE
不能重启任务,新增任务后也无法自动执行，简单说就是：增删改任务后需要重启一次webman

### ISSUE THREAD

**Issue by TNT-ma** [yzh52521/webman-task#10]
增删改任务后需要重启一次webman
太不人性化了
---
任务运行中，我通过接口删除任务，任务还是继续在跑
我启动了webman后，新增任务  任务根本不工作

随便改点什么，增加任务，删除任务，都需要去重启主项目，有点鸡勒

**Comment by TNT-ma** [comment]
> 使用的正常啊 
PHP 8.2   你弄2个：url  试试，重启任务，停止任务，启动任务，随便执行个几次，整个webman 都卡掉，我测试了很多次都是如此

**Comment by yzh52521** [comment]
php 8.2 测试了也没有问题
