### ISSUE TITLE
安装1.4.8版本后出错

### ISSUE THREAD

**Issue by kangsange** [yzh52521/webman-task#11]
安装好之后一切正常，但是只要一增加定时任务，就会报错，但数据库里已存在定时任务信息，报错如下：
`
ArgumentCountError: Too few arguments to function yzh52521\Task\Mutex\RedisTaskMutex::__construct(), 0 passed in /www/wwwroot/hantuzt/vendor/workerman/webman-framework/src/Container.php on line 41 and exactly 1 expected in /www/wwwroot/hantuzt/vendor/yzh52521/webman-task/src/Mutex/RedisTaskMutex.php:17
Stack trace:
#0 /www/wwwroot/hantuzt/vendor/workerman/webman-framework/src/Container.php(41): yzh52521\Task\Mutex\RedisTaskMutex->__construct()
#1 /www/wwwroot/hantuzt/vendor/workerman/webman-framework/src/support/Container.php(46): Webman\Container->get()
#2 /www/wwwroot/hantuzt/vendor/yzh52521/webman-task/src/Server.php(538): support\Container::__callStatic()
#3 /www/wwwroot/hantuzt/vendor/yzh52521/webman-task/src/Server.php(501): yzh52521\Task\Server->getTaskMutex()
#4 /www/wwwroot/hantuzt/vendor/yzh52521/webman-task/src/Server.php(527): yzh52521\Task\Server->runInSingleton()
#5 /www/wwwroot/hantuzt/vendor/yzh52521/webman-task/src/Server.php(248): yzh52521\Task\Server->decorateRunnable()
#6 /www/wwwroot/hantuzt/vendor/yzh52521/webman-task/src/Server.php(165): yzh52521\Task\Server->crontabRun()
#7 /www/wwwroot/hantuzt/vendor/yzh52521/webman-task/src/Server.php(110): yzh52521\Task\Server->crontabInit()
#8 /www/wwwroot/hantuzt/support/helpers.php(432): yzh52521\Task\Server->onWorkerStart()
#9 /www/wwwroot/hantuzt/support/helpers.php(470): worker_bind()
#10 /www/wwwroot/hantuzt/vendor/workerman/workerman/Worker.php(2494): {closure}()
#11 /www/wwwroot/hantuzt/vendor/workerman/workerman/Worker.php(1633): Workerman\Worker->run()
#12 /www/wwwroot/hantuzt/vendor/workerman/workerman/Worker.php(1426): Workerman\Worker::forkOneWorkerForLinux()
#13 /www/wwwroot/hantuzt/vendor/workerman/workerman/Worker.php(1400): Workerman\Worker::forkWorkersForLinux()
#14 /www/wwwroot/hantuzt/vendor/workerman/workerman/Worker.php(1785): Workerman\Worker::forkWorkers()
#15 /www/wwwroot/hantuzt/vendor/workerman/workerman/Worker.php(1721): Workerman\Worker::monitorWorkersForLinux()
#16 /www/wwwroot/hantuzt/vendor/workerman/workerman/Worker.php(562): Workerman\Worker::monitorWorkers()
#17 /www/wwwroot/hantuzt/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#18 /www/wwwroot/hantuzt/start.php(23): support\App::run()
#19 {main}
Workerman[start.php] stopping ...
worker[plugin.yzh52521.task.cron_task:3593] exit with status 64000
`

**Comment by yuanzhihai** [comment]
依赖注入没有安装

**Comment by kangsange** [comment]
已搞定
