### ISSUE TITLE
我看webman的插件介绍有和webman-admin配套使用

### ISSUE THREAD

**Issue by kylin987** [yzh52521/webman-task#6]
安装后在webman-admin的后台没有找到啊

**Comment by kylin987** [comment]
[https://www.workerman.net/upload/img/20220412/12625506364e29.png](url)

**Comment by yzh52521** [comment]
这个是我项目里的截图

**Comment by kylin987** [comment]
方便分享一份吗？我也是用的webman-admin，非常感谢
